### PR TITLE
fix(core): prevent chain_id from serializing for requests

### LINKED ISSUE #877: unknown field chainId when trying to deploy contract with forge
when deploying a contract to kovan with forge create getting the following error

(code: -32602, message: Invalid params: unknown field chainId, expected one of type, from, to, gasPrice, maxFeePerGas, gas, value, data, nonce, accessList, maxPriorityFeePerGas., data: None)

Version: forge 0.1.0 (8107afe 2022-01-31T10:48:23.593667+00:00)

### PR DESCRIPTION
**Pull request by Rjected**
## Motivation
OpenEthereum seems to not have a `chainId` field in its [`TransactionRequest`](https://github.com/openethereum/openethereum/blob/main/crates/rpc/src/v1/types/transaction_request.rs#L32) type.

## Solution
This PR disables serialization for the `chain_id`, so we don't send it in RPC requests.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Updated the changelog

Fixes #877

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
hmm, this is a bit tricky, because I'm not sure what side-effects this could potentially cause, what does? since this is a client issue for openethereum
I believe in geth chainid is omitempty, so this approach seems fine. But not sure if there is some kind of check that chainids match so that tx intended for chain X are rejected on chain Y? so we'd lose that

alternatives:

* should we skip this instead based on the chainid?
* should we rather take the chain id if the client is OE, I believe we already have some calls that check the client first, definitely more effort, not ideal.

**Comment by Rjected** [comment]
Since `chain_id` was [recently](https://github.com/gakonst/ethers-rs/pull/805) introduced to our request types, we shouldn't really be introducing any new issues by not serializing.

I'm not sure that alternative 1 (skip based on the chainid), or any solution that depends on _only_ the chainid would work since OE will not accept any chainId field. [Geth does have omitempty for the chainId](https://github.com/ethereum/go-ethereum/blob/2d20fed893faa894f50af709349b13b6ad9b45db/internal/ethapi/transaction_args.go#L36), but it would be up to us to ensure that the `chain_id` field matches that of the client when running `send_transaction`, `sign_transaction`, etc. This would probably prevent user error.

This would not be necessary for `send_raw_transaction`, since that depends on RLP, which should already include the chainid. [Geth does check the chainId](https://github.com/ethereum/go-ethereum/blob/2d20fed893faa894f50af709349b13b6ad9b45db/core/types/transaction_signing.go#L272), so if we were to do chainId checks there it would be in case other clients don't do these checks.

File: ethers-core/src/types/transaction/request.rs [hunk 1]
```diff
@@ -42,7 +42,8 @@ pub struct TransactionRequest {
     pub nonce: Option<U256>,
 
     /// Chain ID (None for mainnet)
-    #[serde(skip_serializing_if = "Option::is_none")]
+    #[serde(skip_serializing)]
+    #[serde(rename = "chainId")]
```
Comment (mattsse) [inline ethers-core/src/types/transaction/request.rs:46]:
```suggestion
    #[serde(default, rename = "chainId")]
```

**Review by mattsse — CHANGES_REQUESTED** [review]
smol nit

File: ethers-core/src/types/transaction/request.rs (hunk 1 above)
Comment (Rjected) [reply ethers-core/src/types/transaction/request.rs]: added to both request and 1559 request

**Review by gakonst — APPROVED** [review]

**Comment by tarrencev** [comment]
@Rjected I'm still running into this issue after updating foundry to use this PR

```
(code: -32602, message: Invalid params: unknown field `chainId`, expected one of `type`, `from`, `to`, `gasPrice`, `maxFeePerGas`, `gas`, `value`, `data`, `nonce`, `accessList`, `maxPriorityFeePerGas`., data: None)
```

It looks like it is still serialized into the txn `\"chainId\":\"0x2a\"`

**Comment by tarrencev** [comment]
Ah nevermind. I sanity checked forge paths and it was using an old path under `.cargo` rather than the one in `.foundry`
